### ISSUE TITLE
Configuração do módulo não publicada/disponível

### ISSUE THREAD

**Issue by alissonalberini** [cagartner/bagisto-pagseguro#1]
A execução da instalação "composer require cagartner/bagisto-pagseguro", corre bem.

A gestão pela administração ( Admin > Configurar > Vendas > Métodos de Pagamento > Pagseguro.), não ficou acessível.

Verifiquei:

Se  havia algo a publicar, "vendor:publish", nada d novo.
Se havia migrations ou seeders,nada de novo.

Algo a ser feito?

#Resolvido:

run "php artisan config:clear"

**Comment by cagartner** [comment]
Olá Alisson.

Então deu liga quando rodou `php artisan config:clear`?

Me confirma que irei atualizar o doc com essa informação :D

**Comment by alissonalberini** [comment]
Olá @cagartner, sim, apos limpar a config, foi habilitado a gestão pelo painel admin, estou a realizar testes, e ver o que posso mais relatar e ou contribuir.

**Comment by cagartner** [comment]
Obrigado Alisson.

Estou tentando criar uma comunidade Bagisto no Brasil, caso tenha interesse de participar fique a vontade:

Facebook Groups: https://www.facebook.com/groups/2552301808420521
Twitter: http://twitter.com/bagistobr
Whatsapp Grupo: https://chat.whatsapp.com/HpMKEoxf5neIfnpUlHGmaO

Abraços!
