### ISSUE TITLE
ola, eu nao entendi oq para fazer aqui

### ISSUE THREAD

**Issue by marcelowu** [cagartner/bagisto-pagseguro#2]
ola, eu nao entendi oq para fazer aqui

2- Não esqueça de colocar as rotas do pagseguro no exceptions do app/Http/Middleware/VerifyCsrfToken.php:

/**
 * The URIs that should be excluded from CSRF verification.
 *
 * @var array
 */
protected $except = [
    'pagseguro/*'
];

**Comment by cagartner** [comment]
Hey @marcelowu 

Você tem que procurar o arquivo `VerifyCsrfToken.php` no seu projeto, deve estar dentro da pasta `app/Http/Middleware`

E adicionar `'pagseguro/'` dentro do array da variável `$except`.

se você não fizer isso o Laravel irá bloquear as requisições de notificação que o pagseguro enviar ao bagisto.

Parar tirar essas dúvidas favor entre me nossos grupos do Whats: https://chat.whatsapp.com/HpMKEoxf5neIfnpUlHGmaO 

É mais fácil que responder aqui no github :D

**Comment by marcelowu** [comment]
agora entendi. obrigado
