### ISSUE TITLE
Notificação de transações

### ISSUE THREAD

**Issue by marcelowu** [cagartner/bagisto-pagseguro#3]
Notificação de transações como configuro
![Captura de tela de 2020-04-28 21-16-50](https://user-images.githubusercontent.com/30912144/80550261-e696db00-8995-11ea-8c46-746f87c83f45.png)

**Comment by cagartner** [comment]
Primeiramente sua loja precisa estar em um servidor público.

E tem que configurar a excessão do passo 2 da instalação no README do módulos: https://github.com/cagartner/bagisto-pagseguro#instala%C3%A7%C3%A3o

Por padrão o módulo já envia na solicitação de compra a URL de notificação da loja.

Entre no nosso grupo de whats para tirar dúvidas é mais rápido: 

https://chat.whatsapp.com/HpMKEoxf5neIfnpUlHGmaO

**Comment by marcelowu** [comment]
ok, obrigado
