### ISSUE TITLE
Pagseguro: Unauthorized

### ISSUE THREAD

**Issue by joaovdiasb** [cagartner/bagisto-pagseguro#4]
![image](https://user-images.githubusercontent.com/51106311/81229224-d4d0bb80-8fc5-11ea-8c07-71b1fcf138d8.png)

Erro ao enviar pedido, configurei o token e email do pagseguro, o que pode ser?

**Comment by cagartner** [comment]
Olá @joaovdiasb 

você está testando em qual modo? Produção ou Sandbox? Se for sandbox vc precisa pegar os credenciais no site do sandbox: https://sandbox.pagseguro.uol.com.br/

Abraços!

**Comment by joaovdiasb** [comment]
@cagartner realmente, estava marcado o modo sandbox, desmarquei lá e agora me retorna isso
![image](https://user-images.githubusercontent.com/51106311/81239297-da84cc00-8fda-11ea-999e-13810863afb6.png)

**Comment by cagartner** [comment]
Então, para você usar em modo de produção, ele precisa estar publicado em algum servidor, senão o o pagseguro não consegue validar a URL de notificação.

Vejo que você está usando o `php artisan serve`, tenta usar um virtual host na sua máquina, configura um nginx ou apache e tenta novamente com uma URL mais real, como bagisto.local...

Abraços!

**Comment by joaovdiasb** [comment]
Vou configurar um virtual host então pra ver se rola, valeu ai pelo apoio!
